### ISSUE TITLE
Cambio de Logo

### ISSUE THREAD

**Issue by Peredicve** [LKRcoin/lkrcoinn#2]
Actualizar a Logo nuevo 

![image](https://user-images.githubusercontent.com/34489355/50106587-a1da2c00-0206-11e9-99ee-054feebddd51.png)

![image](https://user-images.githubusercontent.com/34489355/50106672-da7a0580-0206-11e9-8911-76cbe20ac9a4.png)

![image](https://user-images.githubusercontent.com/34489355/50106756-19a85680-0207-11e9-94f6-b686295f3123.png)

**Comment by CarmeloCampos** [comment]
Esto ya se realizó hace años <3
