### ISSUE TITLE
~/lkrcoin/src/obj - No such file or directory

### ISSUE THREAD

**Issue by johnnysosa** [LKRcoin/lkrcoinn#4]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

---

alert.cpp:273:1: fatal error: opening dependency file obj/alert.d: No such file or directory
 }
 ^
compilation terminated.
makefile.unix:175: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1

Solution:

sudo mkdir -p ~/lkrcoin/src/obj/zerocoin

The above also fixes the following error:

zerocoin/Accumulator.cpp:106:1: fatal error: opening dependency file obj/zerocoin/Accumulator.d: No such file or directory
 } /* namespace libzerocoin */
 ^
compilation terminated.
makefile.unix:182: recipe for target 'obj/zerocoin/Accumulator.o' failed
make: *** [obj/zerocoin/Accumulator.o] Error 1

**Comment by CarmeloCampos** [comment]
Cuando sucedió esto, clonaste desde github? o descargaste el código ?

**Comment by CarmeloCampos** [comment]
Este error es por que la carpeta obj y la carpeta zerocoin dentro de obj no están creadas.
